/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'accent-blue': '#3b8cf8',
        'error': '#ffb4ab',
        'surface-container-low': '#1a1c1c',
        'primary-fixed-dim': '#c9c6c5',
        'error-container': '#93000a',
        'surface-container-high': '#282a2b',
        'tertiary': '#00e639',
        'on-primary': '#313030',
        'on-secondary-fixed': '#241a00',
        'on-background': '#e2e2e2',
        'surface-container-highest': '#333535',
        'surface-tint': '#c9c6c5',
        'primary-fixed': '#e5e2e1',
        'tertiary-fixed': '#72ff70',
        'surface-bright': '#37393a',
        'on-secondary-fixed-variant': '#574500',
        'inverse-on-surface': '#2f3131',
        'inverse-surface': '#e2e2e2',
        'on-tertiary-fixed': '#002203',
        'background': '#050505',
        'secondary': '#e9c349',
        'on-tertiary': '#003907',
        'surface': '#121414',
        'on-primary-fixed-variant': '#474646',
        'tertiary-container': '#000700',
        'on-secondary-container': '#342800',
        'outline-variant': '#444748',
        'on-secondary': '#3c2f00',
        'tertiary-fixed-dim': '#00e639',
        'outline': '#8e9192',
        'surface-dim': '#121414',
        'primary-container': '#050505',
        'on-primary-fixed': '#1c1b1b',
        'surface-variant': '#333535',
        'surface-container-lowest': '#0c0f0f',
        'on-surface-variant': '#c4c7c7',
        'secondary-fixed-dim': '#e9c349',
        'on-tertiary-fixed-variant': '#00530e',
        'on-error': '#690005',
        'on-primary-container': '#797777',
        'surface-container': '#1e2020',
        'secondary-fixed': '#ffe088',
        'inverse-primary': '#5f5e5e',
        'secondary-container': '#af8d11',
        'on-surface': '#e2e2e2',
        'on-tertiary-container': '#008b1e',
        'on-error-container': '#ffdad6',
        'primary': '#c9c6c5',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-padding-mobile': '20px',
        'container-padding-desktop': '40px',
        'gutter': '16px',
        'unit': '8px',
        'section-gap': '64px',
      },
      fontFamily: {
        'headline-md': ['Montserrat'],
        'body-lg': ['Montserrat'],
        'body-md': ['Montserrat'],
        'display-lg-mobile': ['Montserrat'],
        'display-lg': ['Montserrat'],
        'label-sm': ['JetBrains Mono'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
